on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Read Release Notes
        id: read_release_notes
        run: |
          release_notes=$(cat release_notes.txt)
          echo "RELEASE_NOTES=${release_notes}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
      


      - name: Get changed Python files
        run: | 
          git fetch origin
          BASE_BRANCH=$(git rev-parse origin/main)
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep '^tests/.*\.py$' || true)
          echo "Changed Python Test Files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "base branch: $BASE_BRANCH"

      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies and pytest
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest
        

      - name: Print directory contents
        run: |
          ls -R

      - name: Run affected tests
        run: |
            if [ -n "$CHANGED_FILES" ]; then
              echo "Changed files exist. Running tests."
              echo "Current directory: $(pwd)"
              echo "Files to test: $CHANGED_FILES"
              cd $GITHUB_WORKSPACE
              python -m pytest -v -x "$(echo "$CHANGED_FILES")"
            else
              echo "No Python test files changed. Skipping tests."
            fi 
