on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed Python files
        run: | 
          git fetch origin
          BASE_BRANCH=$(git rev-parse origin/main)
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep '^tests/.*\.py$' || true)
          echo "Changed Python Test Files: $CHANGED_FILES"
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "base branch: $BASE_BRANCH"
        env:
          GITHUB_ENV: ${{ runner.workspace }}/.env

      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Print directory contents
        run: |
          ls -R

      - name: Run affected tests
        if: env.CHANGED_FILES != ''
        run: |
          echo "Running affected tests."
          cd $GITHUB_WORKSPACE
          python -m pytest -v $CHANGED_FILES

      - name: Run all tests
        if: env.CHANGED_FILES == ''
        run: |
          echo "Running all tests."
          cd $GITHUB_WORKSPACE
          python -m pytest -v

      

